// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvwLTGYqrwd4nnBqaHDH7TdUI8nu0JK1g',
    appId: '1:824889863052:web:eeb9b48ed16187985304a9',
    messagingSenderId: '824889863052',
    projectId: 'auth-c9a4e',
    authDomain: 'auth-c9a4e.firebaseapp.com',
    storageBucket: 'auth-c9a4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIHBJYrIVqJ1brQJaSw2nDFC8wFUcCs0',
    appId: '1:824889863052:android:15103099f38efb095304a9',
    messagingSenderId: '824889863052',
    projectId: 'auth-c9a4e',
    storageBucket: 'auth-c9a4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBszg2-YpjnGP15T76wj66uVTDk_OwWbE4',
    appId: '1:824889863052:ios:2222345da7bc9af35304a9',
    messagingSenderId: '824889863052',
    projectId: 'auth-c9a4e',
    storageBucket: 'auth-c9a4e.appspot.com',
    iosBundleId: 'com.example.logIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBszg2-YpjnGP15T76wj66uVTDk_OwWbE4',
    appId: '1:824889863052:ios:480b86c6711117bc5304a9',
    messagingSenderId: '824889863052',
    projectId: 'auth-c9a4e',
    storageBucket: 'auth-c9a4e.appspot.com',
    iosBundleId: 'com.example.logIn.RunnerTests',
  );
}
